[package]
authors = ["Marc Brinkmann <git@marcbrinkmann.de>",
          "Denys Vitali <denys@denv.it>"]
name = "poppler"
license = "GPL-2.0"
version = "0.3.0"
description = "Wrapper for the GPL-licensed Poppler PDF rendering library."
repository = "https://github.com/DMSrs/poppler-rs"
edition = "2018"

[dependencies]
<<<<<<< HEAD
cairo-rs = { features = ["png", "pdf"], version = "0.8.1" }
cairo-sys-rs = "0.9.2"
glib = "0.9.3"
glib-sys = "0.9.1"
gobject-sys = "0.9.1"
=======
poppler-sys = { version = "0.1.0", path = "poppler-sys" }
cairo-rs = { version = "0.6.0", features = ["png", "pdf"]}
glib = "0.7.1"
glib-sys = "0.8.0"
gobject-sys = "0.8.0"

[features]
default = []
generate-bindings = ["poppler-sys/generate-bindings"]
>>>>>>> 72a077ff8e54e5b564518cfc30a4f5ddd1f396bc
